version: "3.8"

services:
  frontend-client:
    build: ./frontend-client/postlt-app
    ports:
      - "5173:5173"
    depends_on:
      - backend-server
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend-server:
    build: ./backend-server
    ports:
      - "8000:8000"
    volumes:
      - ./backend-server:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
